<!-- @migration-task Error while migrating Svelte code: Cannot use `export let` in runes mode — use `$props()` instead
https://svelte.dev/e/legacy_export_invalid -->
<script lang="ts">
	import Indicator from '$lib/components/Indicator.svelte';
	import { onMount } from 'svelte';
	
	// 속성
	const { groupId, onClose } = $props<{
		groupId: string;
		onClose: () => void;
	}>();
	
	// 그룹 데이터 타입
	interface FoodGroup {
		id: string;
		name: string;
		description: string;
		memberCount: number;
		placeCount: number;
		thumbnail: string;
		tags: string[];
		isOfficial: boolean;
		isHot: boolean;
		isNew: boolean;
		isAutoGenerated: boolean;
		type?: string;
		createdAt: string;
		owner: Member;
		joinMethod: 'open' | 'approval';
	}
	
	// 멤버 타입
	interface Member {
		id: string;
		name: string;
		avatar: string;
		role: 'owner' | 'admin' | 'member';
		joinedAt: string;
	}
	
	// 음식점 타입
	interface Place {
		id: string;
		name: string;
		thumbnail: string;
		address: string;
		category: string;
		rating: number;
		reviewCount: number;
		likeCount: number;
		saveCount: number;
		tags: string[];
		addedBy: string;
		addedAt: string;
	}
	
	// 상태 정의
	let loading = $state(true);
	let group = $state<FoodGroup | null>(null);
	let members = $state<Member[]>([]);
	let places = $state<Place[]>([]);
	let activeTab = $state<'places' | 'members' | 'activity'>('places');
	let sortBy = $state<'popular' | 'recent'>('popular');
	let isJoined = $state(false);
	let showAddPlaceModal = $state(false);
	let showManagementModal = $state(false);
	
	// 멤버 더미 데이터
	const dummyMembers: Member[] = [
		{
			id: 'user-1',
			name: '김맛집',
			avatar: 'https://placehold.co/100x100?text=김맛집',
			role: 'owner',
			joinedAt: '2023-01-15'
		},
		{
			id: 'user-2',
			name: '박푸드',
			avatar: 'https://placehold.co/100x100?text=박푸드',
			role: 'admin',
			joinedAt: '2023-01-20'
		},
		{
			id: 'user-3',
			name: '정미식',
			avatar: 'https://placehold.co/100x100?text=정미식',
			role: 'member',
			joinedAt: '2023-02-05'
		},
		{
			id: 'user-4',
			name: '이먹방',
			avatar: 'https://placehold.co/100x100?text=이먹방',
			role: 'member',
			joinedAt: '2023-03-12'
		},
		{
			id: 'user-5',
			name: '최맛있어',
			avatar: 'https://placehold.co/100x100?text=최맛있어',
			role: 'member',
			joinedAt: '2023-04-18'
		}
	];
	
	// 음식점 더미 데이터
	const dummyPlaces: Place[] = [
		{
			id: 'place-1',
			name: '고기야 미안해',
			thumbnail: 'https://placehold.co/300x200?text=고기집',
			address: '서울시 강남구 논현동 123-45',
			category: '고기구이',
			rating: 4.8,
			reviewCount: 245,
			likeCount: 567,
			saveCount: 189,
			tags: ['삼겹살', '소고기', '회식'],
			addedBy: '김맛집',
			addedAt: '2023-01-16'
		},
		{
			id: 'place-2',
			name: '바다의 황제',
			thumbnail: 'https://placehold.co/300x200?text=해산물',
			address: '서울시 마포구 서교동 456-78',
			category: '해산물',
			rating: 4.6,
			reviewCount: 185,
			likeCount: 432,
			saveCount: 156,
			tags: ['회', '해물탕', '가족모임'],
			addedBy: '박푸드',
			addedAt: '2023-02-01'
		},
		{
			id: 'place-3',
			name: '커피가 필요해',
			thumbnail: 'https://placehold.co/300x200?text=카페',
			address: '서울시 용산구 이태원동 789-12',
			category: '카페',
			rating: 4.5,
			reviewCount: 156,
			likeCount: 324,
			saveCount: 98,
			tags: ['커피', '디저트', '데이트'],
			addedBy: '정미식',
			addedAt: '2023-03-02'
		},
		{
			id: 'place-4',
			name: '면의 장인',
			thumbnail: 'https://placehold.co/300x200?text=면요리',
			address: '서울시 서대문구 연희동 345-67',
			category: '국수',
			rating: 4.7,
			reviewCount: 210,
			likeCount: 478,
			saveCount: 132,
			tags: ['라멘', '우동', '혼밥'],
			addedBy: '이먹방',
			addedAt: '2023-04-05'
		},
		{
			id: 'place-5',
			name: '완벽한 피자',
			thumbnail: 'https://placehold.co/300x200?text=피자',
			address: '서울시 강서구 마곡동 789-45',
			category: '양식',
			rating: 4.4,
			reviewCount: 178,
			likeCount: 356,
			saveCount: 87,
			tags: ['피자', '파스타', '친구모임'],
			addedBy: '최맛있어',
			addedAt: '2023-05-10'
		}
	];
	
	// 그룹 더미 데이터
	const dummyGroup: FoodGroup = {
		id: groupId,
		name: '서울 맛집 탐험대',
		description: '서울의 숨겨진 맛집을 함께 발견해요! 가격 대비 만족도가 높은 곳만 엄선합니다. 회원들의 추천과 검증을 통해 신뢰도 높은 맛집 정보를 공유합니다.',
		memberCount: 1245,
		placeCount: 67,
		thumbnail: 'https://placehold.co/800x400?text=서울맛집',
		tags: ['서울', '맛집', '데이트', '혼밥'],
		isOfficial: false,
		isHot: true,
		isNew: false,
		isAutoGenerated: false,
		createdAt: '2023-01-15',
		owner: dummyMembers[0],
		joinMethod: 'open'
	};
	
	// 데이터 로드 함수
	function loadGroupData() {
		loading = true;
		
		// 실제 구현에서는 API 호출
		setTimeout(() => {
			group = dummyGroup;
			members = dummyMembers;
			places = dummyPlaces;
			
			// 가입 여부 체크 (실제로는 사용자 정보와 비교)
			isJoined = true;
			
			loading = false;
		}, 600);
	}
	
	// 탭 변경 함수
	function changeTab(tab: 'places' | 'members' | 'activity') {
		activeTab = tab;
	}
	
	// 정렬 방식 변경
	function changeSortBy(sort: 'popular' | 'recent') {
		sortBy = sort;
		
		// 정렬 적용
		if (sort === 'popular') {
			places = [...places].sort((a, b) => b.likeCount - a.likeCount);
		} else {
			places = [...places].sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime());
		}
	}
	
	// 그룹 가입/탈퇴 함수
	function toggleJoin() {
		isJoined = !isJoined;
		
		if (isJoined) {
			// 그룹 가입 API 호출
			console.log('그룹 가입');
		} else {
			// 그룹 탈퇴 API 호출
			console.log('그룹 탈퇴');
		}
	}
	
	// 음식점 추가 모달 토글
	function toggleAddPlaceModal() {
		showAddPlaceModal = !showAddPlaceModal;
	}
	
	// 그룹 관리 모달 토글
	function toggleManagementModal() {
		showManagementModal = !showManagementModal;
	}
	
	// 음식점 좋아요 함수
	function toggleLike(placeId: string) {
		places = places.map(place => {
			if (place.id === placeId) {
				return {
					...place,
					likeCount: place.likeCount + (place.liked ? -1 : 1),
					liked: !place.liked
				};
			}
			return place;
		});
	}
	
	// 음식점 저장 함수
	function toggleSave(placeId: string) {
		places = places.map(place => {
			if (place.id === placeId) {
				return {
					...place,
					saveCount: place.saveCount + (place.saved ? -1 : 1),
					saved: !place.saved
				};
			}
			return place;
		});
	}
	
	// 날짜 포맷팅 함수
	function formatDate(dateString: string): string {
		const date = new Date(dateString);
		return `${date.getFullYear()}.${(date.getMonth() + 1).toString().padStart(2, '0')}.${date.getDate().toString().padStart(2, '0')}`;
	}
	
	// 숫자 포맷팅 함수
	function formatNumber(num: number): string {
		return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
	}
	
	// 페이지 초기화
	onMount(() => {
		loadGroupData();
	});
</script>

<div class="fixed inset-0 bg-black/80 z-50 flex items-center justify-center overflow-hidden">
	<div class="bg-white w-full max-w-lg max-h-screen flex flex-col relative">
		<!-- 닫기 버튼 -->
		<button 
			class="absolute top-4 right-4 z-10 p-2 rounded-full bg-white/80 text-gray-700 hover:bg-white shadow-sm" 
			onclick={onClose}
		>
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</button>
		
		{#if loading}
			<!-- 로딩 화면 -->
			<!-- <div class="flex-1 flex items-center justify-center">
				<div class="animate-spin rounded-full h-16 w-16 border-t-4 border-b-4 border-blue-500"></div>
			</div> -->
			<Indicator text="그룹 정보를 불러오는 중..." />
		{:else if group}
			<!-- 그룹 헤더 -->
			<div class="relative">
				<div class="h-48 overflow-hidden">
					<img src={group.thumbnail} alt={group.name} class="w-full object-cover" />
					<div class="absolute inset-0 bg-gradient-to-b from-black/10 to-black/70"></div>
				</div>
				
				<div class="absolute bottom-4 left-4 text-white">
					<h1 class="text-2xl font-bold">{group.name}</h1>
					<div class="flex items-center text-sm mt-1">
						<span class="mr-2">멤버 {formatNumber(group.memberCount)}명</span>
						<span>음식점 {formatNumber(group.placeCount)}개</span>
					</div>
				</div>
			</div>
			
			<!-- 그룹 정보 -->
			<div class="p-4 border-b border-gray-200">
				<div class="flex justify-between items-center">
					<div class="flex gap-2">
						{#each group.tags as tag}
							<span class="bg-gray-100 text-gray-600 text-xs px-2 py-1 rounded-full">#{tag}</span>
						{/each}
					</div>
					
					{#if isJoined}
						<button 
							class="px-4 py-1.5 rounded-full bg-gray-100 text-gray-700 text-sm font-medium hover:bg-gray-200 transition-colors"
							onclick={toggleJoin}
						>
							탈퇴하기
						</button>
					{:else}
						<button 
							class="px-4 py-1.5 rounded-full bg-blue-500 text-white text-sm font-medium hover:bg-blue-600 transition-colors"
							onclick={toggleJoin}
						>
							참여하기
						</button>
					{/if}
				</div>
				
				<p class="text-gray-700 text-sm mt-3">{group.description}</p>
				
				<div class="flex justify-between items-center mt-3 text-xs text-gray-500">
					<div>
						생성일: {formatDate(group.createdAt)}
					</div>
					<div>
						{group.joinMethod === 'open' ? '누구나 참여 가능' : '승인 후 참여 가능'}
					</div>
				</div>
			</div>
			
			<!-- 탭 메뉴 -->
			<div class="flex border-b border-gray-200">
				<button 
					class="flex-1 py-3 text-sm font-medium transition-colors {activeTab === 'places' ? 'text-blue-600 border-b-2 border-blue-500' : 'text-gray-600 hover:text-gray-800'}"
					onclick={() => changeTab('places')}
				>
					음식점 목록
				</button>
				<button 
					class="flex-1 py-3 text-sm font-medium transition-colors {activeTab === 'members' ? 'text-blue-600 border-b-2 border-blue-500' : 'text-gray-600 hover:text-gray-800'}"
					onclick={() => changeTab('members')}
				>
					멤버 ({formatNumber(members.length)})
				</button>
				<button 
					class="flex-1 py-3 text-sm font-medium transition-colors {activeTab === 'activity' ? 'text-blue-600 border-b-2 border-blue-500' : 'text-gray-600 hover:text-gray-800'}"
					onclick={() => changeTab('activity')}
				>
					활동 내역
				</button>
			</div>
			
			<!-- 탭 콘텐츠 -->
			<div class="flex-1 overflow-y-auto">
				{#if activeTab === 'places'}
					<!-- 음식점 목록 탭 -->
					<div class="p-4">
						<!-- 정렬 옵션 & 추가 버튼 -->
						<div class="flex justify-between mb-4">
							<div class="flex gap-3">
								<button 
									class="text-sm {sortBy === 'popular' ? 'text-blue-600 font-medium' : 'text-gray-500'}"
									onclick={() => changeSortBy('popular')}
								>
									인기순
								</button>
								<button 
									class="text-sm {sortBy === 'recent' ? 'text-blue-600 font-medium' : 'text-gray-500'}"
									onclick={() => changeSortBy('recent')}
								>
									최신순
								</button>
							</div>
							
							{#if isJoined}
								<button 
									class="flex items-center gap-1 text-sm text-blue-600 font-medium"
									onclick={toggleAddPlaceModal}
								>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
										<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
									</svg>
									음식점 추가
								</button>
							{/if}
						</div>
						
						<!-- 음식점 목록 -->
						<div class="space-y-4">
							{#each places as place}
								<div class="bg-white rounded-lg border border-gray-200 overflow-hidden shadow-sm">
									<div class="flex">
										<!-- 음식점 썸네일 -->
										<div class="w-24 h-24 overflow-hidden">
											<img src={place.thumbnail} alt={place.name} class="w-full h-full object-cover" />
										</div>
										
										<!-- 음식점 정보 -->
										<div class="flex-1 p-3">
											<div class="flex justify-between items-start">
												<div>
													<h3 class="font-medium text-gray-900">{place.name}</h3>
													<p class="text-xs text-gray-500 mt-1">{place.address}</p>
													<div class="flex items-center gap-2 mt-1">
														<span class="bg-gray-100 text-gray-600 text-xs px-2 py-0.5 rounded-full">{place.category}</span>
														<div class="flex items-center gap-1">
															<svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3 text-yellow-500" viewBox="0 0 20 20" fill="currentColor">
																<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
															</svg>
															<span class="text-xs font-medium">{place.rating}</span>
															<span class="text-xs text-gray-500">({formatNumber(place.reviewCount)})</span>
														</div>
													</div>
												</div>
												<div class="flex flex-col items-end gap-2">
													<button 
														class="text-gray-500 hover:text-gray-700"
														onclick={() => toggleLike(place.id)}
													>
														<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 {place.liked ? 'text-red-500 fill-red-500' : ''}" viewBox="0 0 24 24" stroke="currentColor" fill="none">
															<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
														</svg>
													</button>
													<button 
														class="text-gray-500 hover:text-gray-700"
														onclick={() => toggleSave(place.id)}
													>
														<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 {place.saved ? 'text-blue-500 fill-blue-500' : ''}" viewBox="0 0 24 24" stroke="currentColor" fill="none">
															<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
														</svg>
													</button>
												</div>
											</div>
											
											<!-- 통계 -->
											<div class="flex items-center gap-4 mt-2 text-xs text-gray-500">
												<div class="flex items-center gap-1">
													<svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
														<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
													</svg>
													<span>{formatNumber(place.likeCount)}</span>
												</div>
												<div class="flex items-center gap-1">
													<svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
														<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
													</svg>
													<span>{formatNumber(place.saveCount)}</span>
												</div>
												<div>추가: {place.addedBy}</div>
											</div>
										</div>
									</div>
								</div>
							{/each}
						</div>
					</div>
				{:else if activeTab === 'members'}
					<!-- 멤버 목록 탭 -->
					<div class="p-4">
						<div class="flex justify-between mb-4">
							<h3 class="text-sm font-medium text-gray-700">전체 멤버 {formatNumber(members.length)}명</h3>
							
							{#if isJoined && (members[0].role === 'owner' || members[0].role === 'admin')}
								<button 
									class="text-sm text-blue-600 font-medium"
									onclick={toggleManagementModal}
								>
									그룹 관리
								</button>
							{/if}
						</div>
						
						<div class="space-y-3">
							{#each members as member}
								<div class="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
									<div class="flex items-center gap-3">
										<div class="w-10 h-10 rounded-full overflow-hidden">
											<img src={member.avatar} alt={member.name} class="w-full h-full object-cover" />
										</div>
										<div>
											<div class="flex items-center gap-2">
												<h4 class="font-medium text-gray-900">{member.name}</h4>
												{#if member.role === 'owner'}
													<span class="bg-red-100 text-red-600 text-xs px-2 py-0.5 rounded-full">그룹장</span>
												{:else if member.role === 'admin'}
													<span class="bg-orange-100 text-orange-600 text-xs px-2 py-0.5 rounded-full">관리자</span>
												{/if}
											</div>
											<p class="text-xs text-gray-500">가입일: {formatDate(member.joinedAt)}</p>
										</div>
									</div>
								</div>
							{/each}
						</div>
					</div>
				{:else if activeTab === 'activity'}
					<!-- 활동 내역 탭 -->
					<div class="p-4">
						<div class="text-center py-8">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-gray-300 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
							</svg>
							<h3 class="text-gray-500 font-medium">최근 활동 내역이 없습니다</h3>
							<p class="text-gray-400 text-sm mt-2">그룹 멤버들의 활동 내역을 확인할 수 있습니다.</p>
						</div>
					</div>
				{/if}
			</div>
		{:else}
			<!-- 그룹을 찾을 수 없는 경우 -->
			<div class="flex-1 flex flex-col items-center justify-center p-4">
				<svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 text-gray-300 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
				</svg>
				<h2 class="text-xl font-bold text-gray-700 mb-2">그룹을 찾을 수 없습니다</h2>
				<p class="text-gray-500 text-center">요청하신 그룹이 존재하지 않거나 접근 권한이 없습니다.</p>
				<button 
					class="mt-6 px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors"
					onclick={onClose}
				>
					돌아가기
				</button>
			</div>
		{/if}
	</div>
</div>

<!-- 음식점 추가 모달 -->
{#if showAddPlaceModal}
	<div class="fixed inset-0 bg-black/80 z-[60] flex items-center justify-center p-4">
		<div class="bg-white rounded-xl w-full max-w-md">
			<!-- 모달 헤더 -->
			<div class="p-4 border-b border-gray-200 flex justify-between items-center">
				<h2 class="text-lg font-bold">음식점 추가하기</h2>
				<button class="p-2" onclick={toggleAddPlaceModal}>
					<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
			
			<!-- 모달 콘텐츠 -->
			<div class="p-4">
				<div class="mb-4">
					<input 
						type="text" 
						placeholder="음식점 이름으로 검색" 
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					/>
				</div>
				
				<div class="text-center py-8">
					<svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-gray-300 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
					</svg>
					<h3 class="text-gray-500 font-medium">음식점을 검색해 보세요</h3>
					<p class="text-gray-400 text-sm mt-2">이름으로 검색하면 결과가 이곳에 표시됩니다.</p>
				</div>
			</div>
		</div>
	</div>
{/if}

<!-- 그룹 관리 모달 -->
{#if showManagementModal}
	<div class="fixed inset-0 bg-black/80 z-[60] flex items-center justify-center p-4">
		<div class="bg-white rounded-xl w-full max-w-md">
			<!-- 모달 헤더 -->
			<div class="p-4 border-b border-gray-200 flex justify-between items-center">
				<h2 class="text-lg font-bold">그룹 관리</h2>
				<button class="p-2" onclick={toggleManagementModal}>
					<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
			
			<!-- 모달 콘텐츠 -->
			<div class="p-4">
				<div class="space-y-4">
					<button class="flex items-center w-full p-3 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors">
						<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
						</svg>
						<span class="font-medium text-gray-700">그룹 정보 수정</span>
					</button>
					
					<button class="flex items-center w-full p-3 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors">
						<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
						</svg>
						<span class="font-medium text-gray-700">멤버 관리</span>
					</button>
					
					<button class="flex items-center w-full p-3 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors">
						<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
						</svg>
						<span class="font-medium text-gray-700">음식점 관리</span>
					</button>
					
					<button class="flex items-center w-full p-3 rounded-lg border border-gray-200 hover:bg-red-50 transition-colors">
						<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-red-500 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
						</svg>
						<span class="font-medium text-red-600">그룹 삭제</span>
					</button>
				</div>
			</div>
		</div>
	</div>
{/if} 