<script lang="ts">
	import { preventDefault } from 'svelte/legacy';

	import { onMount } from 'svelte';
	import Header from './Header.svelte';
	// import Tabs from './Tabs.svelte';
	import Tabs from '$lib/components/ui/Tabs.svelte';
	import GroupDetail from './GroupDetail.svelte';
	import { ScrollManager, ScrollDirection } from '$lib/utils/ScrollManager';
	
	// 그룹 데이터 타입 정의
	interface FoodGroup {
		id: string;
		name: string;
		description: string;
		memberCount: number;
		placeCount: number;
		thumbnail: string;
		tags: string[];
		isOfficial: boolean;
		isHot: boolean;
		isNew: boolean;
		isAutoGenerated: boolean; // 시스템 자동화 그룹 여부
		type?: string; // 그룹 유형 (자동화 그룹용)
	}
	
	// 스크롤 관련 상태
	let scrollableArea: HTMLElement | null = $state(null);
	let showNav = $state(true);
	
	// 스크롤 매니저 인스턴스 생성
	const scrollManager = new ScrollManager({
		headerThreshold: 5,
		debug: false
	});

	// 상세 페이지 표시 상태
	let showDetail = $state(false);
	let selectedGroupId = $state<string | null>(null);
	
	// 카테고리 데이터
	const tabs = [
		{ id: 'all', label: '전체', desc: '모든 그룹을 한눈에 볼 수 있어요.' },
		{ id: 'auto', label: '추천 그룹', desc: '나를 위해 자동으로 생성된 맞춤 그룹이에요.' },
		{ id: 'popular', label: '인기 그룹', desc: '많은 사람들이 참여하고 있는 인기 그룹이에요.' },
		{ id: 'my', label: '내 그룹', desc: '내가 참여하고 있는 그룹을 모아서 보여드려요.' },
		{ id: 'region', label: '지역별', desc: '지역별로 모아둔 맛집 그룹이에요.' }
	];
	
	// 활성 카테고리
	let activeTab = $state(0);
	
	// 검색어
	let searchQuery = $state('');
	
	// 그룹 생성 모달 상태
	let showCreateModal = $state(false);
	
	// 자동화 그룹 데이터 (추천 그룹)
	const automatedGroups: FoodGroup[] = [
		{
			id: 'auto-1',
			name: '내 주변 중식당',
			description: '사용자 위치 기반으로 생성된 중식당 모음',
			memberCount: 0,
			placeCount: 15,
			thumbnail: 'https://placehold.co/600x400?text=중식당',
			tags: ['중식', '근처', '자동화'],
			isOfficial: false,
			isHot: false,
			isNew: true,
			isAutoGenerated: true,
			type: 'location'
		},
		{
			id: 'auto-2',
			name: '내가 저장한 맛집',
			description: '사용자가 저장한 맛집 모음',
			memberCount: 0,
			placeCount: 8,
			thumbnail: 'https://placehold.co/600x400?text=저장맛집',
			tags: ['저장', '맛집', '자동화'],
			isOfficial: false,
			isHot: false,
			isNew: true,
			isAutoGenerated: true,
			type: 'saved'
		},
		{
			id: 'auto-3',
			name: '회식하기 좋은 곳',
			description: '사용자 취향 기반 추천 회식 장소',
			memberCount: 0,
			placeCount: 12,
			thumbnail: 'https://placehold.co/600x400?text=회식',
			tags: ['회식', '단체', '자동화'],
			isOfficial: false,
			isHot: false,
			isNew: true,
			isAutoGenerated: true,
			type: 'recommendation'
		}
	];
	
	// 사용자 생성 그룹 데이터
	const userGroups: FoodGroup[] = [
		{
			id: '1',
			name: '서울 맛집 탐험대',
			description: '서울 숨은 맛집을 찾아서',
			memberCount: 1245,
			placeCount: 67,
			thumbnail: 'https://placehold.co/600x400?text=서울맛집',
			tags: ['서울', '맛집', '데이트'],
			isOfficial: false,
			isHot: true,
			isNew: false,
			isAutoGenerated: false
		},
		{
			id: '2',
			name: '가성비 끝판왕',
			description: '가격 대비 만족도가 높은 식당 모음',
			memberCount: 987,
			placeCount: 42,
			thumbnail: 'https://placehold.co/600x400?text=가성비',
			tags: ['가성비', '저렴', '대학생'],
			isOfficial: false,
			isHot: true,
			isNew: false,
			isAutoGenerated: false
		},
		{
			id: '3',
			name: '혼밥 맛집 컬렉션',
			description: '혼자 먹기 좋은 식당 모음',
			memberCount: 654,
			placeCount: 29,
			thumbnail: 'https://placehold.co/600x400?text=혼밥',
			tags: ['혼밥', '편안함', '1인분'],
			isOfficial: false,
			isHot: false,
			isNew: false,
			isAutoGenerated: false
		},
		{
			id: '4',
			name: '인스타 감성 카페',
			description: '사진 찍기 좋은 감성 카페 모음',
			memberCount: 1032,
			placeCount: 45,
			thumbnail: 'https://placehold.co/600x400?text=감성카페',
			tags: ['카페', '디저트', '인스타그램'],
			isOfficial: false,
			isHot: false,
			isNew: true,
			isAutoGenerated: false
		},
		{
			id: '5',
			name: '고기 마니아',
			description: '고기 맛집 모음',
			memberCount: 876,
			placeCount: 31,
			thumbnail: 'https://placehold.co/600x400?text=고기',
			tags: ['고기', '삼겹살', '소고기'],
			isOfficial: false,
			isHot: true,
			isNew: false,
			isAutoGenerated: false
		}
	];
	
	// 지역별 그룹 데이터
	const regionGroups: FoodGroup[] = [
		{
			id: 'region-1',
			name: '서울 강남구 맛집',
			description: '강남구 지역 맛집 모음',
			memberCount: 1420,
			placeCount: 88,
			thumbnail: 'https://placehold.co/600x400?text=강남맛집',
			tags: ['서울', '강남구', '지역'],
			isOfficial: true,
			isHot: true,
			isNew: false,
			isAutoGenerated: false
		},
		{
			id: 'region-2',
			name: '서울 마포구 맛집',
			description: '마포구 지역 맛집 모음',
			memberCount: 986,
			placeCount: 65,
			thumbnail: 'https://placehold.co/600x400?text=마포맛집',
			tags: ['서울', '마포구', '지역'],
			isOfficial: true,
			isHot: false,
			isNew: false,
			isAutoGenerated: false
		},
		{
			id: 'region-3',
			name: '부산 해운대구 맛집',
			description: '해운대구 지역 맛집 모음',
			memberCount: 754,
			placeCount: 43,
			thumbnail: 'https://placehold.co/600x400?text=해운대맛집',
			tags: ['부산', '해운대구', '지역'],
			isOfficial: true,
			isHot: false,
			isNew: true,
			isAutoGenerated: false
		}
	];
	
	// 모든 그룹 데이터 결합
	let groups = $state([...automatedGroups, ...userGroups, ...regionGroups]);
	
	// 필터링된 그룹
	let filteredGroups = $state<FoodGroup[]>([]);
	
	// 내 그룹 (가입한 그룹)
	const myGroups = ['1', '5', 'region-1']; // 가입한 그룹 ID 목록
	
	// 그룹 필터링 함수
	function filterGroups() {
		if (searchQuery.trim() !== '') {
			// 검색어가 있으면 검색어로 필터링
			filteredGroups = groups.filter(group => 
				group.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
				group.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
				group.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()))
			);
		} else {
			// 카테고리별 필터링
			const currentTab = tabs[activeTab].id;
			switch(currentTab) {
				case 'auto':
					filteredGroups = groups.filter(group => group.isAutoGenerated);
					break;
				case 'popular':
					filteredGroups = groups.filter(group => group.isHot && !group.isAutoGenerated);
					break;
				case 'my':
					filteredGroups = groups.filter(group => myGroups.includes(group.id));
					break;
				case 'region':
					filteredGroups = regionGroups;
					break;
				default:
					filteredGroups = groups;
			}
		}
	}
	
	// 카테고리 변경 함수
	function handleTabChange(index: number) {
		activeTab = index;
		searchQuery = '';
		filterGroups();
		
		// 스크롤을 맨 위로 이동
		scrollManager.scrollToTop('auto');
	}
	
	// 검색 함수
	function handleSearch(event: Event) {
		event.preventDefault();
		filterGroups();
	}
	
	// 그룹 생성 모달 토글
	function toggleCreateModal() {
		showCreateModal = !showCreateModal;
	}
	
	// 숫자 포맷팅 (1000 -> 1,000)
	function formatNumber(num: number): string {
		return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
	}
	
	// 그룹 클릭 핸들러
	function handleGroupClick(groupId: string) {
		console.log(`그룹 클릭: ${groupId}`);
		selectedGroupId = groupId;
		showDetail = true;
	}
	
	// 상세 페이지 닫기
	function closeDetail() {
		showDetail = false;
		selectedGroupId = null;
	}
	
	// 초기 데이터 로드 및 스크롤 관련 설정
	onMount(() => {
		// 초기 필터링
		filterGroups();
		
		// 스크롤 매니저 초기화
		const cleanup = scrollManager.initialize();
		
		// 스크롤 컨테이너 요소 설정
		if (scrollableArea) {
			scrollManager.setContainerElement(scrollableArea);
		}
		
		// 위로 스크롤 시 헤더 표시
		const unsubscribeScrollUp = scrollManager.onDirectionChange(
			ScrollDirection.UP,
			() => {
				if (!showNav) {
					showNav = true;
				}
			}
		);
		
		// 아래로 스크롤 시 헤더 숨김
		const unsubscribeScrollDown = scrollManager.onDirectionChange(
			ScrollDirection.DOWN,
			() => {
				if (showNav) {
					showNav = false;
				}
			}
		);
		
		// 컴포넌트 정리 함수 반환
		return () => {
			cleanup();
			unsubscribeScrollUp();
			unsubscribeScrollDown();
		};
	});
	
	// 그룹 생성 폼 데이터
	let newGroup = $state({
		name: '',
		description: '',
		isPrivate: false,
		tags: [] as string[],
		category: ''
	});
	
	// 태그 입력 관리
	let tagInput = $state('');
	
	// 태그 추가
	function addTag() {
		if (tagInput.trim() && !newGroup.tags.includes(tagInput.trim())) {
			newGroup.tags = [...newGroup.tags, tagInput.trim()];
			tagInput = '';
		}
	}
	
	// 태그 삭제
	function removeTag(tag: string) {
		newGroup.tags = newGroup.tags.filter(t => t !== tag);
	}
	
	// 그룹 생성 처리
	function createGroup() {
		console.log('새 그룹 생성:', newGroup);
		// 실제로는 여기서 API 호출하여 그룹 생성
		toggleCreateModal();
		// 폼 초기화
		newGroup = {
			name: '',
			description: '',
			isPrivate: false,
			tags: [],
			category: ''
		};
	}
	
	// 프로필 클릭 핸들러
	function handleProfileClick() {
		// 프로필 클릭 처리
		console.log('프로필 클릭');
	}
	
	// 검색 클릭 핸들러
	function handleSearchClick() {
		// 검색 클릭 처리
		console.log('검색 클릭');
	}
	
	// 그룹 생성 클릭 핸들러
	function handleCreateGroupClick() {
		showCreateModal = true;
		console.log('그룹 생성 클릭');
	}
</script>

<div class="scroll-container" bind:this={scrollableArea}>
	<div class="fixed top-0 left-0 right-0 z-30 transition-transform duration-300 ease-in-out bg-white"
		 style="transform: translateY({showNav ? '0' : '-100%'})">
		<Header 
			on:profileClick={handleProfileClick}
			on:searchClick={handleSearchClick}
			on:createGroupClick={handleCreateGroupClick}
		/>
		<Tabs 
			tabs={tabs} 
			activeTab={activeTab} 
			onChange={handleTabChange} 
		/>
	</div>
	
	<!-- 메인 컨텐츠 -->
	<div class="mx-auto max-w-lg px-0 py-4 pt-30 pb-45 sm:px-4">
		<!-- 탭 설명 박스 -->
		<!-- <div class="mb-2 p-3 bg-gray-50 rounded-lg border border-gray-200">
			<div class="flex items-center gap-2 text-gray-700">
				<span class="text-lg">💡</span>
				<p class="text-sm font-medium">{tabs[activeTab].desc}</p>
			</div>
		</div> -->

		{#if filteredGroups.length > 0}
			<!-- 추천 그룹 섹션 -->
			{#if tabs[activeTab].id === 'auto' && filteredGroups.filter(g => g.isAutoGenerated).length > 0}
				<div class="mb-8">
					<h2 class="text-lg font-bold mb-4">나를 위한 맞춤 그룹</h2>
					
					<div class="space-y-4">
						{#each filteredGroups.filter(g => g.isAutoGenerated) as group}
							<div 
								class="bg-white rounded-xl overflow-hidden border border-gray-200 shadow-sm"
								onclick={() => handleGroupClick(group.id)}
							>
								<div class="relative h-36 overflow-hidden">
									<img src={group.thumbnail} alt={group.name} class="w-full h-full object-cover" />
									<div class="absolute inset-0 bg-gradient-to-b from-black/10 to-black/70"></div>
									<div class="absolute bottom-3 left-3 text-white">
										<h3 class="font-bold">{group.name}</h3>
										<p class="text-xs text-white/80 mt-1">{group.description}</p>
									</div>
								</div>
								<div class="p-3 flex justify-between items-center">
									<div class="flex items-center gap-3 text-xs text-gray-500">
										<div class="flex items-center gap-1">
											<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
											</svg>
											<span>{formatNumber(group.placeCount)}개</span>
										</div>
									</div>
									<button class="px-3 py-1 rounded-full bg-purple-50 text-purple-600 font-medium hover:bg-purple-100 transition-colors">
										둘러보기
									</button>
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/if}
			
			<!-- 일반 그룹 목록 -->
			<div class="space-y-4">
				{#each filteredGroups.filter(g => !g.isAutoGenerated || tabs[activeTab].id !== 'auto') as group}
					<div 
						class="bg-white rounded-xl overflow-hidden border border-gray-200 shadow-sm"
						onclick={() => handleGroupClick(group.id)}
					>
						<div class="flex">
							<div class="w-24 h-24 overflow-hidden">
								<img src={group.thumbnail} alt={group.name} class="w-full h-full object-cover" />
							</div>
							<div class="flex-1 p-3 flex flex-col">
								<div class="flex items-center">
									<h3 class="font-bold text-gray-900">{group.name}</h3>
									{#if group.isOfficial}
										<span class="ml-2 px-1.5 py-0.5 bg-blue-100 text-blue-600 text-xs rounded-full">공식</span>
									{/if}
									{#if group.isNew}
										<span class="ml-2 px-1.5 py-0.5 bg-green-100 text-green-600 text-xs rounded-full">NEW</span>
									{/if}
									{#if group.isHot}
										<span class="ml-2 px-1.5 py-0.5 bg-red-100 text-red-600 text-xs rounded-full">HOT</span>
									{/if}
								</div>
								<p class="text-xs text-gray-500 mt-1 line-clamp-2">{group.description}</p>
								<div class="flex flex-wrap gap-1 mt-1">
									{#each group.tags.slice(0, 3) as tag}
										<span class="px-1.5 py-0.5 bg-gray-100 text-gray-600 text-xs rounded-full">#{tag}</span>
									{/each}
								</div>
								<div class="mt-auto pt-2 flex justify-between items-center">
									<div class="flex items-center gap-3 text-xs text-gray-500">
										<div class="flex items-center gap-1">
											<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
											</svg>
											<span>{formatNumber(group.memberCount)}명</span>
										</div>
										<div class="flex items-center gap-1">
											<svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
											</svg>
											<span>{formatNumber(group.placeCount)}개</span>
										</div>
									</div>
									{#if !group.isAutoGenerated && !myGroups.includes(group.id)}
										<button class="px-3 py-1 rounded-full bg-blue-50 text-blue-600 font-medium hover:bg-blue-100 transition-colors">
											참여하기
										</button>
									{:else if !group.isAutoGenerated && myGroups.includes(group.id)}
										<button class="px-3 py-1 rounded-full bg-gray-100 text-gray-500 font-medium hover:bg-gray-200 transition-colors">
											탈퇴하기
										</button>
									{:else}
										<button class="px-3 py-1 rounded-full bg-purple-50 text-purple-600 font-medium hover:bg-purple-100 transition-colors">
											둘러보기
										</button>
									{/if}
								</div>
							</div>
						</div>
					</div>
				{/each}
			</div>
		{:else}
			<!-- 검색 결과 없음 -->
			<div class="bg-white rounded-xl p-8 text-center">
				<svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-gray-400 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
				</svg>
				<p class="text-gray-500 text-lg mb-2">검색 결과가 없습니다</p>
				<p class="text-gray-400 text-sm">다른 검색어로 시도해보세요</p>
			</div>
		{/if}
	</div>
</div>

<!-- 그룹 상세 모달 -->
{#if showDetail && selectedGroupId}
	<GroupDetail 
		groupId={selectedGroupId}
		onClose={closeDetail}
	/>
{/if}

<!-- 그룹 생성 모달 -->
{#if showCreateModal}
	<div class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
		<div class="bg-white rounded-xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
			<!-- 헤더 -->
			<div class="p-4 border-b border-gray-200 flex justify-between items-center">
				<h2 class="text-lg font-bold">새 그룹 만들기</h2>
				<button 
					class="p-1 rounded-full hover:bg-gray-100"
					onclick={toggleCreateModal}
				>
					<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
					</svg>
				</button>
			</div>
			
			<!-- 폼 -->
			<div class="p-4">
				<div class="mb-4">
					<label for="group-name" class="block text-sm font-medium text-gray-700 mb-1">그룹 이름</label>
					<input 
						id="group-name"
						type="text" 
						bind:value={newGroup.name}
						placeholder="그룹 이름 입력"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					/>
				</div>
				
				<div class="mb-4">
					<label for="group-description" class="block text-sm font-medium text-gray-700 mb-1">그룹 설명</label>
					<textarea 
						id="group-description"
						bind:value={newGroup.description}
						placeholder="그룹에 대한 설명을 입력하세요"
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
						rows="3"
					></textarea>
				</div>
				
				<div class="mb-4">
					<label for="group-tags" class="block text-sm font-medium text-gray-700 mb-1">태그</label>
					<div class="flex items-center mb-2">
						<input 
							id="group-tags"
							type="text" 
							bind:value={tagInput}
							onkeydown={(e) => e.key === 'Enter' && addTag()}
							placeholder="태그 입력 후 Enter"
							class="flex-1 px-3 py-2 border border-gray-300 rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
						/>
						<button 
							class="px-3 py-2 bg-blue-500 text-white rounded-r-md hover:bg-blue-600"
							onclick={addTag}
						>
							추가
						</button>
					</div>
					
					{#if newGroup.tags.length > 0}
						<div class="flex flex-wrap gap-2">
							{#each newGroup.tags as tag}
								<div class="inline-flex items-center gap-1 bg-gray-100 px-2 py-1 rounded-full">
									<span class="text-xs text-gray-800">#{tag}</span>
									<button 
										class="text-gray-500 hover:text-gray-700"
										onclick={() => removeTag(tag)}
									>
										<svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
											<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
										</svg>
									</button>
								</div>
							{/each}
						</div>
					{/if}
				</div>
				
				<div class="mb-4">
					<label for="group-category" class="block text-sm font-medium text-gray-700 mb-1">카테고리</label>
					<select 
						id="group-category"
						bind:value={newGroup.category}
						class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
					>
						<option value="">카테고리 선택</option>
						<option value="restaurant">식당</option>
						<option value="cafe">카페</option>
						<option value="bar">술집</option>
						<option value="activity">액티비티</option>
						<option value="other">기타</option>
					</select>
				</div>
				
				<div class="mb-6">
					<label class="flex items-center">
						<input 
							type="checkbox" 
							bind:checked={newGroup.isPrivate}
							class="h-4 w-4 text-blue-500 border-gray-300 rounded focus:ring-blue-500"
						/>
						<span class="ml-2 text-sm text-gray-700">비공개 그룹으로 만들기</span>
					</label>
					<p class="text-xs text-gray-500 mt-1 pl-6">비공개 그룹은 초대를 통해서만 가입할 수 있습니다.</p>
				</div>
				
				<!-- 제출 버튼 -->
				<div class="flex justify-end">
					<button 
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 mr-2"
						onclick={toggleCreateModal}
					>
						취소
					</button>
					<button 
						class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600"
						onclick={createGroup}
						disabled={!newGroup.name.trim() || !newGroup.description.trim()}
					>
						생성하기
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

<style>
	/* 스크롤바 숨기기 */
	.scroll-container {
		height: 100vh;
		overflow-y: auto;
		overflow-x: hidden;
		width: 100%;
		position: fixed;
		top: 0;
		left: 0;
		overscroll-behavior-y: contain;
		-webkit-overflow-scrolling: touch;
	}
	
	.scroll-container::-webkit-scrollbar {
		display: none;
	}
	
	/* 최대 2줄까지 표시 */
	.line-clamp-2 {
		overflow: hidden;
		display: -webkit-box;
		-webkit-line-clamp: 2;
		-webkit-box-orient: vertical;
	}
</style>